#!/bin/bash
# setup_env.sh — Check for required credentials, prompt if missing, write to .env

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

# Load existing .env if present
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE" 2>/dev/null || true
  set +a
fi

# Required variables and their prompts
REQUIRED_VARS=(
  "OPENWEBUI_ADMIN_PASSWORD:Open WebUI admin password (for chat login and model import)"
)
OPTIONAL_VARS=(
  "OPENWEBUI_ADMIN_EMAIL:Open WebUI admin email (default: admin@local)"
)

# Build MISSING list (optional first so we prompt email before password)
MISSING=()
for entry in "${OPTIONAL_VARS[@]}"; do
  key="${entry%%:*}"
  if [ -z "${!key}" ]; then
    MISSING+=("$entry")
  fi
done
for entry in "${REQUIRED_VARS[@]}"; do
  key="${entry%%:*}"
  if [ -z "${!key}" ]; then
    MISSING+=("$entry")
  fi
done

if [ ${#MISSING[@]} -eq 0 ]; then
  exit 0
fi

# Interactive setup
echo ""
echo "=============================================="
echo "  do-rag Setup — Required Credentials"
echo "=============================================="
echo ""
echo "A few details are needed for first-time setup."
echo "These will be saved to .env (not committed to git)."
echo ""

for entry in "${MISSING[@]}"; do
  key="${entry%%:*}"
  prompt="${entry#*:}"
  default=""

  case "$key" in
    OPENWEBUI_ADMIN_EMAIL)
      default="admin@local"
      echo -n "$prompt [$default]: "
      read -r value
      value="${value:-$default}"
      ;;
    OPENWEBUI_ADMIN_PASSWORD)
      echo -n "$prompt: "
      read -rs value
      echo ""
      if [ -z "$value" ]; then
        echo "Password cannot be empty."
        exit 1
      fi
      echo -n "Confirm password: "
      read -rs confirm
      echo ""
      if [ "$value" != "$confirm" ]; then
        echo "Passwords do not match."
        exit 1
      fi
      ;;
    *)
      echo -n "$prompt: "
      read -r value
      ;;
  esac

  export "$key=$value"
done

# Write .env
{
  echo "# do-rag credentials (generated by setup)"
  echo "# Edit this file to change values. Run ./run.sh to apply."
  echo ""
  for entry in "${REQUIRED_VARS[@]}" "${OPTIONAL_VARS[@]}"; do
    key="${entry%%:*}"
    if [ -n "${!key}" ]; then
      val="${!key}"
      # Escape double quotes and backslashes for .env
      val="${val//\\/\\\\}"
      val="${val//\"/\\\"}"
      printf '%s="%s"\n' "$key" "$val"
    fi
  done
} > "$ENV_FILE"

echo ""
echo "Credentials saved to .env"
echo ""
exit 0
